### ISSUE TITLE
[Q] 请问您的博客的`代码高亮`是用什么插件弄得?

### ISSUE THREAD

**Issue by Guang1234567** [crimx/blog#1]
Hello crimx:

请问您的博客的`代码高亮`是用什么插件弄得? 谢谢.

**Comment by crimx** [comment]
这个 hexo 自带的，应该是 highlighter ，样式我自己对 tomorrow night 主题修改了一番 https://github.com/crimx/blog/blob/master/themes/crimx/source/_scss/libs/_codeblock.scss

**Comment by Guang1234567** [comment]
多谢, 我看看先
